// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrY-VCJM2pKUFHLgJnl9f3UFb21JSmG2U',
    appId: '1:201599614693:android:5b34e8e3e33b882c989e0c',
    messagingSenderId: '201599614693',
    projectId: 'quickchats-652a8',
    storageBucket: 'quickchats-652a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-IajDrSSSEaaVq0-ci7BHgijEhucodYE',
    appId: '1:201599614693:ios:689014bc33f5f80f989e0c',
    messagingSenderId: '201599614693',
    projectId: 'quickchats-652a8',
    storageBucket: 'quickchats-652a8.appspot.com',
    androidClientId:
        '201599614693-280du79uoa7mefqffhljihfro0kssloj.apps.googleusercontent.com',
    iosClientId:
        '201599614693-kir8284f92tplapurfcuv368eth8b58c.apps.googleusercontent.com',
    iosBundleId: 'com.quick_chats',
  );
}
